### ISSUE TITLE
Tie ndnmap and ndndemo together so they get updates in sync

### ISSUE THREAD

**Issue by jdehart1** [WU-ARL/NDN_Ansible#26]
ndnmap and ndndemo use a lot of the same information about nodes/sites in the Testbed.
ndn-fch service relies on ndnmap but ndnmap usually lags behind ndndemo in updates when something gets added or changed.

Perhaps we can support both of them on the same machine. Right now they are on separate machines.
Or perhaps we can generate the config files from Ansible and push them out to each of them from one place.

**Comment by Pesa** [comment]
ndnmap is no longer maintained.
