### ISSUE TITLE
Contact operators of all currently down NDN Testbed nodes

### ISSUE THREAD

**Issue by WU-ARL** [WU-ARL/NDN_Ansible#33]
REMAP: Email sent(8/15). JeffB says they'll check on it in the next day or two. (8/15)
BUPT: Email sent(8/15).  Guijin Zou responded (8/16) that they are still interested. Working on setting up the node again.
CNIC: This is just an issue of ndndemo status page not being able to contact it. Node is up. I can log in.
PKUSZ: Email sent(8/15)
TONGJI: Email sent(8/15). Received email from operator (8/23). Machine back up now.
BYU: Email sent(8/15)
SYSTEMX: Email sent(8/15)
INDONESIA: Email sent(8/15)
CAGLIARI: Email sent(8/15)
CAIDA: Email sent (8/15). Dan rebooted and it is back. (8/16).
SRRU: Email send (8/15).  Thongchai responded (8/16). They are working on it.

Try to clear them all up or remove them before NDNCOMM

**Comment by Pesa** [comment]
stale
